name: apptentive_flutter_example
description: Demonstrates how to use the apptentive_flutter plugin.
publish_to: 'none'

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  apptentive_flutter:
    path: ../

  cupertino_icons: ^1.0.2
  firebase_core: 1.10.5
  firebase_messaging: ^11.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
